#!/usr/bin/env guile
!#
;;; nanocode - minimal claude code alternative (Guile Scheme)
(use-modules (web client) (web request) (web response) (web uri)
             (json) (ice-9 textual-ports) (ice-9 popen) (ice-9 rdelim))

(define KEY (getenv "ANTHROPIC_API_KEY"))
(define MODEL (or (getenv "MODEL") "claude-sonnet-4-20250514"))
(define R "\x1b[0m") (define B "\x1b[1m") (define D "\x1b[2m")
(define C "\x1b[36m") (define G "\x1b[32m") (define BL "\x1b[34m")

(define (tool name input)
  (cond
    ((string=? name "read")
     (call-with-input-file (assoc-ref input "path")
       (lambda (port)
         (let loop ((lines '()) (i 1))
           (let ((line (read-line port)))
             (if (eof-object? line)
                 (string-join (reverse lines) "\n")
                 (loop (cons (format #f "~a| ~a" i line) lines) (1+ i))))))))
    ((string=? name "write")
     (call-with-output-file (assoc-ref input "path")
       (lambda (port) (display (assoc-ref input "content") port))) "ok")
    ((string=? name "bash")
     (let* ((port (open-input-pipe (assoc-ref input "cmd")))
            (output (get-string-all port)))
       (close-pipe port) output))
    ((string=? name "glob")
     (let* ((port (open-input-pipe (format #f "find . -name '~a' | head -50" (assoc-ref input "pat"))))
            (output (get-string-all port)))
       (close-pipe port) output))
    ((string=? name "grep")
     (let* ((port (open-input-pipe (format #f "grep -rn '~a' . | head -50" (assoc-ref input "pat"))))
            (output (get-string-all port)))
       (close-pipe port) output))
    (else "unknown")))

(define schema (json-string->scm "[{\"name\":\"read\",\"description\":\"Read\",\"input_schema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"}},\"required\":[\"path\"]}},{\"name\":\"write\",\"description\":\"Write\",\"input_schema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\"},\"content\":{\"type\":\"string\"}},\"required\":[\"path\",\"content\"]}},{\"name\":\"bash\",\"description\":\"Run\",\"input_schema\":{\"type\":\"object\",\"properties\":{\"cmd\":{\"type\":\"string\"}},\"required\":[\"cmd\"]}},{\"name\":\"glob\",\"description\":\"Find\",\"input_schema\":{\"type\":\"object\",\"properties\":{\"pat\":{\"type\":\"string\"}},\"required\":[\"pat\"]}},{\"name\":\"grep\",\"description\":\"Search\",\"input_schema\":{\"type\":\"object\",\"properties\":{\"pat\":{\"type\":\"string\"}},\"required\":[\"pat\"]}}]"))

(define (ask messages)
  (let* ((body (scm->json-string `(("model" . ,MODEL) ("max_tokens" . 4096) ("system" . "Concise assistant") ("messages" . ,(list->vector messages)) ("tools" . ,schema))))
         (port (open-input-pipe (format #f "curl -s https://api.anthropic.com/v1/messages -H 'Content-Type: application/json' -H 'anthropic-version: 2023-06-01' -H 'x-api-key: ~a' -d '~a'" KEY body))))
    (let ((resp (json-string->scm (get-string-all port))))
      (close-pipe port) resp)))

(format #t "~ananocode~a | ~a~a~a~%~%" B R D MODEL R)
(let loop ((messages '()))
  (format #t "~a~a❯~a " B BL R) (force-output)
  (let ((input (string-trim-both (or (read-line) ""))))
    (cond
      ((eof-object? input) #f)
      ((string=? input "") (loop messages))
      ((string=? input "/q") #f)
      ((string=? input "/c") (format #t "~a⏺ Cleared~a~%" G R) (loop '()))
      (else
       (let ((messages (append messages (list `(("role" . "user") ("content" . ,input))))))
         (let agent-loop ((messages messages))
           (let* ((resp (ask messages))
                  (content (vector->list (assoc-ref resp "content")))
                  (results '()))
             (for-each
              (lambda (block)
                (cond
                  ((string=? (assoc-ref block "type") "text")
                   (format #t "~%~a⏺~a ~a" C R (assoc-ref block "text")))
                  ((string=? (assoc-ref block "type") "tool_use")
                   (let ((name (assoc-ref block "name")))
                     (format #t "~%~a⏺ ~a~a~%" G name R)
                     (let ((result (tool name (assoc-ref block "input"))))
                       (format #t "  ~a⎿ ~a~a~%" D (car (string-split result #\newline)) R)
                       (set! results (append results (list `(("type" . "tool_result") ("tool_use_id" . ,(assoc-ref block "id")) ("content" . ,result))))))))))
              content)
             (let ((messages (append messages (list `(("role" . "assistant") ("content" . ,(list->vector content)))))))
               (if (null? results)
                   (begin (newline) (loop messages))
                   (agent-loop (append messages (list `(("role" . "user") ("content" . ,(list->vector results)))))))))))))))
